=== ematipico/ematipico.xyz/.astro/collections/projects.schema.json
{
  "$ref": "#/definitions/projects",
  "definitions": {
    "projects": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "githubUrl": {
          "type": "string",
          "format": "uri"
        },
        "iconUrl": {
          "type": "string",
          "format": "uri"
        },
        "contributions": {
          "type": "string"
        },
        "order": {
          "type": "number"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "description",
        "githubUrl",
        "iconUrl"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== ematipico/ematipico.xyz/src/content/projects/astro.json
{
	"name": "Astro",
	"description": "The web framework for content-driven websites",
	"githubUrl": "https://github.com/withastro/astro",
	"iconUrl": "https://github.com/withastro.png",
	"contributions": "I am currenlty part of the Core Team. I contributed to the project by implementing the middleware feature, and the edge middleware system for some the official adapters. New build system, i18n and CSP.",
	"order": 2
}
